controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\UsersModel;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionAboutus()
    {
        return $this->render('aboutus');
    }
    public function actionMahsulotlar()
    {
        return $this->render('mahsulotlar');
    }
    public function actionCommunication()
    {
        return $this->render('communication');
    }
    public function actionBrand()
    {
        return $this->render('brand');
    }
    public function actionCard()
    {
        return $this->render('card');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if(Yii::$app->user->identity->getRole() === 'Admin'){
                return $this->redirect('/admin');
            }
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionAccount()
    {
        if(Yii::$app->user->isGuest){
            return $this->redirect('login');
        }
        return $this->render('account');
    }

    public function actionRegistration()
    {
        $model = new UsersModel();
        
        return $this->render('registration',compact('model'));
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/aboutus.php
<div class="brand_color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2 data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Biz har doim siz bilan</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- about -->
<div class="about">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-5 col-md-5 co-sm-l2">
                <div class="about_img" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                    <figure><img src="/images/about.png" alt="img" /></figure>
                </div>
            </div>
            <div class="col-xl-7 col-lg-7 col-md-7 co-sm-l2">
                <div class="about_box">
                    <span data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Bizning do'konimiz</span>
                    <p data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti beatae sit sapiente repudiandae velit consectetur distinctio incidunt sequi, architecto vel!</p>

                </div>
            </div>
            <div class="col-xl-7 col-lg-7 col-md-7 co-sm-l2">
                <div class="about_box_ ">
                    <span data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Bizning do'konimiz</span>
                    <p data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ex! Tempore est nihil odit aliquam ad eum id quas, accusantium voluptatem veritatis deserunt harum magnam earum voluptatibus? Nesciunt, rerum non?</p>

                </div>
            </div>
            <div class="col-xl-5 col-lg-5 col-md-5 co-sm-l2">
                <div class="about_img" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                    <figure><img src="/images/about.png" alt="img" /></figure>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/account.php
<?php

echo "Account page: ". Yii::$app->user->identity->full_name;
echo '<br>';
echo "ID: ". Yii::$app->user->identity->getId();

?>

views/site/brand.php
<div class="brand_color">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2>Tanlangan mahsulot</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-5 mb-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="images p-3">
                                <div class="text-center p-4" data-aos="flip-left"> <img id="main-image" src="/web/images/images/a32.jpeg" width="450" > </div>
                                <div class="row thumbnail text-center" style="border-style: none;">
                                <img onclick="change_image(this)" data-aos="flip-left" src="/images/images/a32 red.jpg" width="200">
                                <img onclick="change_image(this)" data-aos="flip-right" src="/images/images/a32 blue.jfif" width="200">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="product p-4">
                                <div class="d-flex justify-content-between align-items-center" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                    <div class="d-flex align-items-center"> <a href="index.html" ><i class="fa fa-long-arrow-left"></i> <span class="ml-1">Orqaga</span></a>  </div> 
                                    <i style="color: red !important; " class="fa fa-shopping-cart fa-2x text-muted"></i>
                                </div>
                                <div class="mt-4 mb-3"> 
                                    <span class="text-uppercase text-muted brand_a" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Samsung</span>
                                    <h5 class="text-uppercase"  data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Samsung Galaxy A32 4/64GB Awesome Black</h5>
                                    <ul class="d-flex" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                        <li><img src="/images/star.png" alt=""></li>
                                        <li><img src="/images/star.png" alt=""></li>
                                        <li><img src="/images/star.png" alt=""></li>
                                        <li><img src="/images/star.png" alt=""></li>

                                    </ul>
                                    
                                </div>
                                <hr style="background: red;">
                                <p class="about_t" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Qisqacha ma’lumot
                                    Kafolat muddati (oy): 12<br>
                                    
                                    Operatsion sistema versiyasi: Android 11<br>
                                    
                                    Doimiy xotira hajmi: 64GB<br>
                                    
                                    Face ID Datchigi: Mavjud<br>
                                    
                                    Ishlab chiqaruvchi: Vetnam<br>
                                    
                                    Siz Samsung Galaxy A32 4/64GB sotib olish uchun nafaqat Toshkent, balki Andijon, Buxoro, Farg'ona, Jizzax, Xorazm, Namangan, Navoiy, Qashqadaryo, Qoraqalpog'iston Respublikasi, Samarqand, Sirdaryo, Surxondaryo, Toshkent viloyatidan buyurtma berishingiz mumkin. Siz :brend muddatli to'lovga sotib olishingiz mumkin. Samsung Galaxy A32 4/64GB kreditga olib nima qilasiz, bo'lib to'lashga olish osonroq va tezroq bo'lsa? O'zbekiston bo'ylab juda tez yetkazib beramiz.</p>
                                <div class="sizes mt-5" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                    <div class="price d-flex flex-row align-items-center"> <span class="act-price">$20</span>
                                        <div class="ml-2"> <small class="dis-price">$59</small> <span>40% OFF</span> </div>
                                    </div>
                                    <h6 class="text-uppercase">Color</h6> 
                                    <div class="row">
                                        <label class="radio" style="background:black"> 
                                            <input type="radio" name="size" value="" checked>
                                            <span>black</span> 
                                        </label> 
                                        <label class="radio" style="background: blue;"> 
                                            <input type="radio" name="size" value="" checked>
                                            <span>blue</span>
                                        </label> 
                                        <label class="radio" style="background: white;"> 
                                            <input type="radio" name="size" value="">
                                            <span>white</span>
                                        </label> 
                                        <label class="radio" style="background: DarkBlue;"> 
                                            <input type="radio" name="size" value=""> 
                                            <span>DarkBlue</span> 
                                        </label> 
                                        <label class="radio" style="background: red;"> 
                                            <input type="radio" name="size" value=""> 
                                            <span>red</span> 
                                        </label>
                                    </div>
                                </div>
                                <div class="cart mt-4 align-items-center"> <a href="/site/card"><button class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</button></a> <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i> </div>
                                <h3 class="mt-3" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"> O'zbekiston buylab yetkaziberish xizmati</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    <!--comentare-->

    <div class="container mb-5 mt-5">
        <div class="row">
            <div class="panel panel-default widget">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-comment"></span>
                    <h3 class="panel-title" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Xabar</h3>
                    <span class="label label-info">
                        78</span>
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                    <img src="https://avatarmaker.net/images/1.png" class="img-circle img-responsive" alt="" /></div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <a href="http://www.jquery2dotnet.com/2013/10/google-style-login-page-desing-usign.html">
                                            Google Style Login Page Design Using</a>
                                        <div class="mic-info" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                            By: <a href="#">Shamshod </a> on  30 Iyul  2021
                                        </div>
                                    </div>
                                    <div class="comment-text" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                        Awesome design
                                    </div>
                                    
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                    <img src="https://i.pinimg.com/originals/7f/79/6d/7f796d57218d9cd81a92d9e6e8e51ce4.png" class="img-circle img-responsive" alt="" /></div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <a href="http://bootsnipp.com/BhaumikPatel/snippets/Obgj">Admin Panel Quick Shortcuts</a>
                                        <div class="mic-info" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                            By: <a href="#">RedFox</a> on 30 Iyul 2021
                                        </div>
                                    </div>
                                    <div class="comment-text" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                                        euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim
                                    </div>
                                    
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                    <img src="https://i.pinimg.com/originals/0f/61/91/0f6191cd0b4177c1a1b5e0ea2f872148.png" class="img-circle img-responsive" alt="" /></div>
                                <div class="col-xs-10 col-md-11">
                                    <div data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                        <a href="http://bootsnipp.com/BhaumikPatel/snippets/4ldn">Cool Sign Up</a>
                                        <div class="mic-info">
                                            By: <a href="#">Odil</a> on  25 Iyul  2021
                                        </div>
                                    </div>
                                    <div class="comment-text" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                                        euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim
                                    </div>
                                    
                                </div>
                            </div>
                        </li>
                    </ul>
                    <a href="#" class="btn btn-primary btn-sm btn-block" role="button" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"><span class="glyphicon glyphicon-refresh"></span> More</a>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function() {

                $(this).addClass('transition');
            }, function() {

                $(this).removeClass('transition');
            });
        });

        function change_image(image){

        var container = document.getElementById("main-image");

        container.src = image.src;
        }



        document.addEventListener("DOMContentLoaded", function(event) {


        });
    </script>

views/site/card.php
<div class="brand_color">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="titlepage">
                            <h2 data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Tanlangan mahsulotlar</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>




        <div class="container mt-5 mb-5 p-3 rounded cart">
            <div class="row no-gutters">
                <div class="col-md-8">
                    <div class="product-details mr-2">
                        <div class="d-flex flex-row align-items-center"> <a href="brand.html"><i class="fa fa-long-arrow-left"></i><span class="ml-2">Orqaga</span></a></div>
                        <hr>
                        <h6 class="mb-0" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Shopping cart</h6>
                        <div class="d-flex justify-content-between" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"><span>You have 4 items in your cart</span>
                            <div class="d-flex flex-row align-items-center"><span class="text-black-50">Sort by:</span>
                                <div class="price ml-2"><span class="mr-1">price</span><i class="fa fa-angle-down"></i></div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-3 p-2 items rounded" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <div class="d-flex flex-row"><img class="rounded" src="https://cdn.goodzone.uz/goodzone/4e2093fd-50f8-4185-aee3-c0f8ad44476f" width="40">
                                <div class="ml-2"><span class="font-weight-bold d-block">Iphone 11 pro</span><span class="spec">256GB, Navy Blue</span></div>
                            </div>
                            <div class="d-flex flex-row align-items-center"><span class="d-block">2</span><span class="d-block ml-5 font-weight-bold">$900</span><i class="fa fa-trash-o ml-3 text-black-50"></i></div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-3 p-2 items rounded" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <div class="d-flex flex-row"><img class="rounded" src="https://avatars.mds.yandex.net/get-mpic/4415357/img_id4311518799121644816.jpeg/14hq" width="40">
                                <div class="ml-2"><span class="font-weight-bold d-block">One pro 7T</span><span class="spec">256GB, Navy Blue</span></div>
                            </div>
                            <div class="d-flex flex-row align-items-center"><span class="d-block">2</span><span class="d-block ml-5 font-weight-bold">$900</span><i class="fa fa-trash-o ml-3 text-black-50"></i></div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-3 p-2 items rounded" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <div class="d-flex flex-row"><img class="rounded" src="https://avatars.mds.yandex.net/get-mpic/4076910/img_id2690313567866349770.jpeg/orig" width="40">
                                <div class="ml-2"><span class="font-weight-bold d-block">Google pixel 4 XL</span><span class="spec">256GB, Axe black</span></div>
                            </div>
                            <div class="d-flex flex-row align-items-center"><span class="d-block">1</span><span class="d-block ml-5 font-weight-bold">$800</span><i class="fa fa-trash-o ml-3 text-black-50"></i></div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-3 p-2 items rounded" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <div class="d-flex flex-row"><img class="rounded" src="https://fan-android.com/uploads/posts/2019-08/1565293545_samsung-galaxy-note10-1565212599-0-12.png" width="40">
                                <div class="ml-2"><span class="font-weight-bold d-block">Samsung galaxy Note 10&nbsp;</span><span class="spec">256GB, Navy Blue</span></div>
                            </div>
                            <div class="d-flex flex-row align-items-center"><span class="d-block">1</span><span class="d-block ml-5 font-weight-bold">$999</span><i class="fa fa-trash-o ml-3 text-black-50"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="payment-info" >
                        <div class="d-flex justify-content-between align-items-center"><span>Card details</span><img class="rounded" src="https://www.twowaymirrors.com/wp-content/uploads/2018/06/max-braun-avatar.jpg" width="30"></div><span class="type d-block mt-3 mb-1">Card type</span><label class="radio"> <input type="radio" name="card" value="payment" checked> <span><img width="30" src="https://img.icons8.com/color/48/000000/mastercard.png" /></span> </label>
                        <label class="radio"> <input type="radio" name="card" value="payment"> <span><img width="30" src="https://img.icons8.com/officel/48/000000/visa.png" /></span> </label>
                        <label class="radio"> <input type="radio" name="card" value="payment"> <span><img width="30" src="https://img.icons8.com/ultraviolet/48/000000/amex.png" /></span> </label>
                        <label class="radio"> <input type="radio" name="card" value="payment"> <span><img width="30" src="https://img.icons8.com/officel/48/000000/paypal.png" /></span> </label>
                        <div><label class="credit-card-label">Name on card</label><input type="text" class="form-control credit-inputs" placeholder="Name"></div>
                        <div><label class="credit-card-label">Card number</label><input type="text" class="form-control credit-inputs" placeholder="0000 0000 0000 0000"></div>
                        <div class="row" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <div class="col-md-6"><label class="credit-card-label" >Date</label><input type="text" class="form-control credit-inputs" placeholder="12/24"></div>
                            <div class="col-md-6"><label class="credit-card-label">CVV</label><input type="text" class="form-control credit-inputs" placeholder="342"></div>
                        </div>
                        <hr class="line">
                        <div class="d-flex justify-content-between information" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"><span>Subtotal</span><span>$3000.00</span></div>
                        <div class="d-flex justify-content-between information" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"><span>Shipping</span><span>$20.00</span></div>
                        <div class="d-flex justify-content-between information" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"><span>Total(Incl. taxes)</span><span>$3020.00</span></div><button class="btn btn-primary btn-block d-flex justify-content-between mt-3" type="button"><span>$3020.00</span><span>Checkout<i class="fa fa-long-arrow-right ml-1"></i></span></button>
                    </div>
                </div>
            </div>
        </div>

views/site/communication.php
<div class="brand_color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2 data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Aloqa</h2>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- contact -->
<div class="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <form class="main_form">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <input class="form-control" placeholder="Your name" type="text" name="Your Name">
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <input class="form-control" placeholder="Email" type="text" name="Email">
                        </div>
                        <div class=" col-md-12" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <input class="form-control" placeholder="Phone" type="text" name="Phone">
                        </div>
                        <div class="col-md-12" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                            <textarea class="textarea" placeholder="Message"></textarea>
                        </div>
                        <div class=" col-md-12">
                            <button class="send" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end contact -->

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>



<div class="site-login">
    <div class="brand_color">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2 data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"><?= Html::encode($this->title) ?></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    
                    <?php $form = ActiveForm::begin([
                        'id' => 'login-form',
                        'layout' => 'horizontal',
                        'fieldConfig' => [
                            'template' => "{label}\n<div>{input}</div>\n<div>{error}</div>",
                            'labelOptions' => ['class' => 'col-lg-1 control-label'],
                        ],
                    ]); ?>
                    
                    <div class=" col-md-12">
                        <p>Please fill out the following fields to login:</p>
                        <br />
                        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
                    </div>
                    <div class=" col-md-12">
                        <?= $form->field($model, 'password')->passwordInput() ?>
                    </div>
                    <div class=" col-md-12">
                        <?= $form->field($model, 'rememberMe')->checkbox([
                            'template' => "<div>{input} {label}</div>\n<div>{error}</div>",
                        ]) ?>
                    </div>

                    <div class="form-group row">
                        <div class="col-lg-3 ml-3">
                            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                        </div>
                        <div class="col-lg-6">
                            <?= Html::a('Registration', ['site/registration']) ?>
                        </div>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>